-- M-07 (Availability and Scheduling).
--
-- 1. New table `doctor_scheduling_settings` — generated by `drizzle-kit
--    generate` from `src/schema/doctor-scheduling-settings.schema.ts`.
--
-- 2. Two hand-written CHECK constraints on the pre-existing
--    `doctor_availability` table (added in migration 0000, before M-07
--    existed). Hand-written, not drizzle-kit-generated, because the
--    condition is a three-way per-`rule_type` branch that drizzle-kit's
--    `check()` builder has no cleaner way to express than the same raw SQL
--    below — see the doc comment on `doctorAvailabilityTable` in
--    `src/schema/doctor-availability.schema.ts` for the full shape rule and
--    why overlap prevention is deliberately NOT a DB constraint here
--    (enforced in `availability-rule.service.ts` instead).
CREATE TABLE "doctor_scheduling_settings" (
	"doctor_id" uuid PRIMARY KEY NOT NULL,
	"min_notice_minutes" smallint,
	"booking_horizon_days" smallint,
	"slot_interval_minutes" smallint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "doctor_scheduling_settings" ADD CONSTRAINT "doctor_scheduling_settings_doctor_id_doctors_id_fk" FOREIGN KEY ("doctor_id") REFERENCES "public"."doctors"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
-- Binds `rule_type` to its required columns. `weekly` needs a day-of-week
-- and both times, no specific date. `custom_hours` needs a specific date and
-- both times, no day-of-week. `blocked` needs a specific date, no
-- day-of-week, and either no times at all (a full-day block) or both times
-- (a partial-day block) — never just one.
ALTER TABLE "doctor_availability" ADD CONSTRAINT "doctor_availability_rule_shape_check" CHECK (
	(
		"doctor_availability"."rule_type" = 'weekly'
		AND "doctor_availability"."day_of_week" IS NOT NULL
		AND "doctor_availability"."specific_date" IS NULL
		AND "doctor_availability"."start_time" IS NOT NULL
		AND "doctor_availability"."end_time" IS NOT NULL
	)
	OR (
		"doctor_availability"."rule_type" = 'custom_hours'
		AND "doctor_availability"."day_of_week" IS NULL
		AND "doctor_availability"."specific_date" IS NOT NULL
		AND "doctor_availability"."start_time" IS NOT NULL
		AND "doctor_availability"."end_time" IS NOT NULL
	)
	OR (
		"doctor_availability"."rule_type" = 'blocked'
		AND "doctor_availability"."day_of_week" IS NULL
		AND "doctor_availability"."specific_date" IS NOT NULL
		AND (
			("doctor_availability"."start_time" IS NULL AND "doctor_availability"."end_time" IS NULL)
			OR ("doctor_availability"."start_time" IS NOT NULL AND "doctor_availability"."end_time" IS NOT NULL)
		)
	)
);
--> statement-breakpoint
-- Whenever both times are present (any rule_type), the range must be
-- non-empty and forward — end strictly after start.
ALTER TABLE "doctor_availability" ADD CONSTRAINT "doctor_availability_time_order_check" CHECK (
	"doctor_availability"."start_time" IS NULL
	OR "doctor_availability"."end_time" IS NULL
	OR "doctor_availability"."end_time" > "doctor_availability"."start_time"
);