import type { PatientFileCategory } from '../../schema/enums.schema';

/** One `patient_files` row, as seen from OUTSIDE this module — never carries `storageKey` (`patient-files.schema.ts`: "never exposed to the client", which applies equally to another module reaching through the facade). */
export interface PatientFileView {
  id: string;
  fileCategory: PatientFileCategory;
  patientId: string | null;
  uploadedByDoctorId: string | null;
  consultationId: string | null;
  reportRequestId: string | null;
  clarificationCaseId: string | null;
  fileName: string;
  createdAt: Date;
}

/**
 * Document's public surface — deliberately ONE method today, same restraint
 * as `catalogue.contract.ts`/`availability.contract.ts`: `getPatientFileById`
 * is the read a near-term consumer would plausibly need first — M-15
 * (clinical records) or M-11 (booking) resolving a document reference by id
 * without needing to know this module's internal row shape or storage key.
 *
 * *** THE SECOND METHOD ARRIVED THE WAY THIS COMMENT SAID IT WOULD. *** This
 * header used to read "no write method exists here yet for 'a future M-15 will
 * write [prescription_pdf] through your facade, not through HTTP'
 * (`docs/MODULES.md`'s M-10 section) — that is a documented INTENTION for when
 * M-15 exists and has a real, specific shape to ask for, not something to build
 * speculatively now." M-15 now exists and asked for one specific shape, so
 * `writePrescriptionPdf` is here and nothing else came with it.
 *
 * Still nothing for the de-identified clarification-attachment path: M-17 does
 * not exist, so that stays an intention on exactly the same terms. See
 * `report-request.service.ts`'s header comment.
 */
export interface DocumentContract {
  /** One file by id, or `null` if it does not exist or is soft-deleted. No ownership check — this is a trusted module-to-module call; the CALLING module is responsible for its own authorization before deciding to call it, same as `AvailabilityContract`'s methods carry no auth checks either. */
  getPatientFileById(fileId: string): Promise<PatientFileView | null>;

  /**
   * *** ADDITIVE (M-15). THE WRITE THIS CONTRACT'S HEADER SAID WOULD ARRIVE
   * WHEN SOMETHING REAL ASKED FOR IT. ***
   *
   * `docs/MODULES.md`'s M-10 section: "a future M-15 writes [prescription_pdf]
   * through your facade, not through HTTP". M-15 now exists and has a concrete
   * shape to ask for, so the intention becomes a method — and it stays the ONLY
   * door, because `patient-file.service.ts#validateCategory` rejects
   * `prescription_pdf` BY NAME on the patient upload path. That rejection and
   * this method are two halves of one rule: a prescription is generated by the
   * platform from a finalised clinical record, never uploaded by anyone.
   *
   * *** IDEMPOTENT ON `consultationId`. *** A consultation has at most one live
   * prescription PDF (`clinical_records.consultation_id` is UNIQUE, so there is
   * at most one record to render). If a non-deleted `prescription_pdf` already
   * exists for the consultation it is RETURNED UNCHANGED and `pdf` is
   * discarded — nothing is stored, no second row appears. M-15 finalises, then
   * generates; a retried finalise, an operator re-trigger and the doctor's
   * explicit "regenerate" call all land here, and none of them may fork a
   * patient\'s record into two prescriptions.
   *
   * No ownership check — a trusted module-to-module call. M-15 has already
   * established that the caller is the treating doctor and that the record is
   * finalised; this module stores the bytes and owns the row.
   *
   * `pdf` is a `Buffer` rather than a base64 string. `backend/README.md` §1 asks
   * facade methods to pass JSON-safe objects so a local call can become a
   * network one, and a Buffer is the one deliberate exception here — it is
   * exactly what `DocumentStoragePort.store` already takes across this module\'s
   * other seam, and base64-ing a megabyte of PDF through an in-process call to
   * satisfy a future TCP transport would cost 33% on every real call today for
   * a hop that does not exist. A TCP extraction would encode it at the
   * transport, which is where that decision belongs.
   */
  writePrescriptionPdf(input: WritePrescriptionPdfInput): Promise<PatientFileView>;

  /**
   * ADDITIVE (M-21/data rights execution): `DataRightsFacade#previewExecution`
   * needs a READ-ONLY row count of what this module holds for a patient's
   * approved data-deletion request, without touching a single row — this
   * module's tables are RETAIN in the M-21 compliance survey (SRS §5.3
   * retention obligations), so nothing here is ever anonymized or deleted.
   *
   * `patientFiles` counts every non-deleted `patient_files` row for
   * `patientId` directly, REGARDLESS of `consultationIds` — a file such as
   * `medical_history` can be attached to no consultation at all and is still
   * the patient's. `reportRequests` counts `report_requests` rows whose
   * `consultation_id` is one of `consultationIds`, resolved by the caller
   * the same way `patient-file.repository.ts#listForDoctorHistory` already
   * expects a caller-resolved consultation set.
   */
  countDataRightsRowsForPatient(input: {
    patientId: string;
    consultationIds: readonly string[];
  }): Promise<{ patientFiles: number; reportRequests: number }>;
}

/** See `DocumentContract#writePrescriptionPdf`. */
export interface WritePrescriptionPdfInput {
  /** The consultation the prescription belongs to. Also the idempotency key. */
  consultationId: string;
  /** The patient the record is about — becomes `patient_files.patient_id`, which is what makes the file visible on their own `GET /documents/me`. */
  patientId: string;
  /** The treating doctor — becomes `patient_files.uploaded_by_doctor_id`, so a patient cannot delete a prescription issued to them (`patient-file.service.ts#deleteOwn` refuses any file with that column set). */
  doctorId: string | null;
  /** Shown to the patient in their downloads. */
  fileName: string;
  /** The rendered PDF. */
  pdf: Buffer;
}
